name: Build All - Monthly 

on:
  schedule:
    # every 5. of a month night at 0:47h rebuild dev and latest
            #  ┌───────────── minute (0 - 59)
            #  │ ┌───────────── hour (0 - 23)
            #  │ │ ┌───────────── day of the month (1 - 31)
            #  │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
            #  │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    - cron:  '47 0 5 * *'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push latest Image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:latest"
          push: true
          tags: jayar79/chordpro:latest
      -
        name: Build and push DEV Image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:dev"
          push: true
          tags: jayar79/chordpro:dev
      -
        name: Build and push MASTER Image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:master"
          push: true
          tags: jayar79/chordpro:master          