name: Build and Push Dev-Image 

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push DEV Image
        uses: docker/build-push-action@v3
        with:
#       context: ./dev
          dockerfile: ./dev/Dockerfile
          push: true
          tags: jayar79/chordpro:dev